name: Test-the-flow
on: [push]
jobs:
  first-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: ls -la

      - name: Hello world action step
        id: hello
        uses: actions/CD-CI-TEST@v1
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"


      - run: echo 'Hello world !$!' > test.txt
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: test.txt-file
          path: test.txt
