name: Test-the-flow
on: [push]
jobs:
  first-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: ls -la




      - run: echo 'Hello world !$!' > test.txt
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: test.txt-file
          path: test.txt
