name: Test-the-flow
on: [push]
jobs:
  first-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Print-string
        run: echo 'Hello world !$!'
      - run: echo 'Hello world !$!' > test.txt
      - run: cat test.txt
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: test.txt-file
          path: test.txt
