name: build

on:
  push:
  pull_request:
    branches:
      - fpga

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up env
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - run: sudo apt install verilator
    - run: verilator -Wall -cc ./src/top.sv --Mdir .
    - run: ls -alF
    - run: make -f Vtop.mk
    - run: g++ -I /usr/share/verilator/include/ -I . /usr/share/verilator/include/verilated.cpp src/top.cpp Vtop__ALL.a -o run_top
    - run: ls -alF
    - run: ./run_top
    - run: ls -alF
