name: build

on:
  push:
  pull_request:
    branches:
      - fpga

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up env
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - run: sudo apt install verilator
    - run: verilator -Wall -cc ./src/top.sv
    - run: cd obj_dir/
    - run: make -f Vtop.mk
    - run: cd ..
    - run: g++ -I /usr/share/verilator/include/ -I obj_dir/ /usr/share/verilator/include/verilated.cpp src/top.cpp obj_dir/Vtop__ALL.a -o run_top
