name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${python: "3.7"}

    - name: Install requierement
      run: pip install -r requirements.txt

    - name: Pytest
      run: python -m pytest
